// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://*************************.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_apiKey": "*********************************"
};



export default awsmobile;